spring.application.name=supnum
spring.autoconfigure.exclude=org.springframework.boot.webmvc.autoconfigure.error.ErrorMvcAutoConfiguration

# Swagger/OpenAPI Configuration
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.tryItOutEnabled=true
springdoc.swagger-ui.display-request-duration=true
springdoc.swagger-ui.filter=true
springdoc.swagger-ui.doc-expansion=none
springdoc.swagger-ui.default-model-rendering=model
springdoc.swagger-ui.supported-submit-methods=get,post,put,delete,patch